// Phase 6 types — manually maintained alongside Rust DTOs.
// These supplement the generated bindings.ts (gitignored, regenerated by cargo test).
// Synced with crates/trackly-app/src/dto/printer.rs and dto/request.rs.

/**
 * Public printer DTO — what the UI receives.
 * Synced with crates/trackly-app/src/dto/printer.rs PrinterDto.
 * All fields camelCase (serde rename_all = "camelCase").
 */
export type PrinterDto = {
  id: number;
  deviceId: number;
  ipAddress: string | null;
  snmpVersion: string;
  vendor: string | null;
  oidProfileId: number | null;
  lastSeenUtc: number | null;
  communityConfigured: boolean;
  deviceName: string | null;
  deviceLocation: string | null;
  usbHostDeviceId: number | null;
  /** Parsed toner levels: Object { label: number|null } or null if no reading. */
  tonerLevels: Record<string, number | null> | null;
  pageCount: number | null;
  status: string | null;
  hasAlert: boolean;
  alertType: string | null;
  /** Current cartridge installed in this printer (PRN-07, D-PRN07-01). */
  currentCartridgeId: number | null;
  version: number;
};

/**
 * Filter parameters for printer list queries.
 */
export type PrinterFilter = {
  status: string | null;
  search: string | null;
};

/**
 * Input DTO for creating a printer record.
 */
export type PrinterCreateDto = {
  deviceId: number;
  ipAddress: string | null;
  communityUpdate: string | null;
  snmpVersion: string;
  oidProfileId: number | null;
  usbHostDeviceId: number | null;
};

/**
 * A printer found during SNMP discovery scan.
 */
export type DiscoveredPrinterDto = {
  ip: string;
  vendor: string | null;
  model: string | null;
  sysName: string;
  oidProfileId: number | null;
  /** True if a printer with this IP already exists in the DB. */
  isDuplicate: boolean;
};

/**
 * Paginated printer list response.
 */
export type PrinterListResponse = {
  items: PrinterDto[];
  total: number;
};

/**
 * A single printer status reading (history entry).
 */
export type PrinterReadingDto = {
  id: number;
  printerId: number;
  tsUtc: number;
  tonerLevelsJson: string;
  pageCount: number | null;
  status: string;
};

/**
 * Public request DTO — what the UI receives.
 * Synced with crates/trackly-app/src/dto/request.rs RequestDto.
 */
export type RequestDto = {
  id: number;
  requestType: string;
  status: string;
  requestedByUserId: number;
  assignedToUserId: number | null;
  printerDeviceId: number | null;
  cartridgeModelId: number | null;
  categoryId: number | null;
  completedCartridgeId: number | null;
  description: string | null;
  resolutionNotes: string | null;
  requesterName: string | null;
  printerName: string | null;
  createdAtUtc: number;
  updatedAtUtc: number;
  deletedAtUtc: number | null;
  version: number;
  /**
   * Phase 9 (V028 migration): "register" | "restore" | null — only set when
   * `requestType === 'ad_register'`. See bindings-phase9.ts
   * RequestDtoAdSubtype doc-comment.
   */
  adSubtype: 'register' | 'restore' | null;
  /**
   * D-CAT-01 (Phase 11): joined `request_categories.name` — display name for
   * `categoryId`. `null` when the request has no category set.
   */
  categoryName: string | null;
  /**
   * D-05 (Phase 12 Plan 01): joined `locations.name` via the request's
   * printer device (`devices.location_id`). `null` for `free_form` requests
   * (no printer) and for printers without a location set.
   */
  printerLocation: string | null;
};

/**
 * A single request category option `{ id, name }` (D-CAT-01).
 * Synced with crates/trackly-app/src/dto/request.rs RequestCategoryDto.
 */
export type RequestCategoryDto = {
  id: number;
  name: string;
};

/**
 * A single printer option `{ id, name, location }` for the create-request
 * form's printer dropdown (D-PRN-01, Phase 11 Plan 02).
 * Synced with crates/trackly-app/src/dto/request.rs RequestPrinterOptionDto.
 *
 * Deliberately minimal — no SNMP/community/IP/serial fields. This is what
 * the `request_printer_options` endpoint returns (CreateRequest-gated, NOT
 * ReadData/ReadPrinters which Phase 10 closed for Employee).
 */
export type RequestPrinterOptionDto = {
  id: number;
  name: string;
  location: string | null;
};

/**
 * Filter parameters for request list queries.
 */
export type RequestFilter = {
  status: string | null;
  requestType: string | null;
  assignedToUserId: number | null;
  requestedByUserId: number | null;
};

/**
 * Request list response.
 */
export type RequestListResponse = {
  items: RequestDto[];
  total: number;
};

/**
 * Input DTO for creating a new request.
 */
export type RequestCreateDto = {
  requestType: string;
  printerDeviceId: number | null;
  cartridgeModelId: number | null;
  categoryId: number | null;
  description: string | null;
};

/**
 * Request lifecycle transition payload.
 */
export type RequestTransitionPayload =
  | { op: 'accept'; requestId: number; version: number; assignedToUserId: number | null }
  | { op: 'reject'; requestId: number; version: number; notes: string | null }
  | {
      op: 'complete';
      requestId: number;
      version: number;
      notes: string | null;
      linkedCartridgeId: number | null;
    };

/**
 * Aggregate counts for the request status switch-bar.
 */
export type RequestCountsDto = {
  all: number;
  open: number;
  inProgress: number;
  completed: number;
  rejected: number;
};

/**
 * WebSocket broadcast event — synced with Rust WsEvent enum.
 * `type` field is snake_case per serde tag = "type", rename_all = "snake_case".
 * NOTE: 'request_status_changed' — NOT 'request_updated'.
 */
export type WsEvent =
  | { type: 'new_request'; requestId: number; requestType: string; requesterName: string }
  | {
      type: 'request_status_changed';
      requestId: number;
      newStatus: string;
      requestedByUserId: number;
    }
  | { type: 'printer_alert'; printerId: number; printerName: string; alertType: string };
