// Phase 9 types — manually maintained alongside Rust DTOs.
// These supplement the generated bindings.ts (gitignored, regenerated by cargo test).
// Synced with crates/trackly-app/src/dto/auth.rs and dto/request.rs.

/**
 * Login request body — POST /api/v1/auth_login + Tauri `auth_login`.
 * Synced with crates/trackly-app/src/dto/auth.rs LoginRequest.
 * snake_case on the wire (dto/auth.rs convention — no rename_all; see
 * `snake_case_json_invariant` test).
 *
 * `remember` (D-UX-02, Phase 9 Plan 04): `#[serde(default)]` — omitting the
 * field is equivalent to `false`.
 * - `true`  → persistent sliding-30-day cookie (`Expiry::OnInactivity`).
 * - `false` (or absent) → session-only cookie, cleared on browser close
 *   (`Expiry::OnSessionEnd`).
 */
export type LoginRequest = {
  login: string;
  password: string;
  remember: boolean;
};

/**
 * AD settings — response of `settings_get_ad`, also the read-model shown
 * by `settings_set_ad`'s caller after a successful save.
 * Synced with crates/trackly-app/src/dto/auth.rs AdSettingsDto.
 * snake_case on the wire (dto/auth.rs convention).
 *
 * `enabled`/`auto_accept` — live source of truth in `app_settings`
 * (ManageSettings-gated, admin-only). `host`/`port`/`domain`/`base_dn`/
 * `name_attr`/`no_tls_verify` — READ-ONLY bootstrap config from
 * `trackly.config.toml` (`AdConfig`); NOT settable via `settings_set_ad`.
 *
 * T-09-17 / D-Sec-01: the AD bind password NEVER appears in this DTO —
 * grep-gated (`ad_settings_dto_roundtrip` test).
 */
export type AdSettingsDto = {
  enabled: boolean;
  auto_accept: boolean;
  host: string;
  port: number;
  domain: string;
  base_dn: string;
  name_attr: string;
  no_tls_verify: boolean;
};

/**
 * Request body — POST /api/v1/settings_set_ad + Tauri `settings_set_ad`.
 * Synced with crates/trackly-app/src/http/auth.rs SetAdPayload.
 * camelCase on the wire (http/auth.rs payload-wrapper convention, matches
 * SetNetworkPayload in http/settings.rs).
 *
 * Only `enabled`/`auto_accept` are writable — connection fields
 * (host/port/domain/...) are read-only TOML bootstrap config, not part of
 * this payload (see AdSettingsDto doc above).
 */
export type SetAdPayload = {
  enabled: boolean;
  autoAccept: boolean;
};

/**
 * Approve an `ad_register` request — admin selects the role to grant
 * (or accepts the default "employee").
 * Synced with crates/trackly-app/src/dto/request.rs ApproveAdRegisterDto.
 * camelCase on the wire (dto/request.rs convention).
 *
 * Used by both `requests_approve_ad_register` (HTTP + Tauri) — built in
 * Plan 03. Listed here for Phase 9 completeness.
 */
export type ApproveAdRegisterDto = {
  requestId: number;
  version: number;
  /** "admin" | "manager" | "employee" — defaults to "employee" if null (D-REG-02). */
  role: string | null;
};

/**
 * RequestDto extension (Phase 9 Plan 03, V028 migration) — NOT a separate
 * type, documents the new field added to the existing RequestDto in
 * bindings.ts / dto/request.rs.
 *
 * `adSubtype`: "register" | "restore" | null — only set when
 * `requestType === 'ad_register'`. Distinguishes a brand-new AD account
 * needing moderation ("register") from a blocked/soft-deleted local
 * account auto-creating a restoration request after a successful AD bind
 * ("restore", created server-side inside `AuthService::login` →
 * `on_ad_bind_success`, no dedicated endpoint).
 */
export type RequestDtoAdSubtype = 'register' | 'restore' | null;

/**
 * `ad_test_connection` (Phase 9 gap-closure) — POST /api/v1/ad_test_connection
 * + Tauri `ad_test_connection`. No request body, no response payload: success
 * is `void` (HTTP 200 / Tauri `Ok(())`), failure is the standard `AppError`
 * envelope (`code: "SERVICE_UNAVAILABLE"` when AD is unreachable).
 *
 * Verifies AD server reachability WITHOUT any end-user credentials (LDAPS
 * connect + anonymous bind, see `AdClient::test_connection` in
 * crates/trackly-core/src/ports/ad.rs). ManageSettings-gated, same as
 * `settings_set_ad` — only an admin can trigger it.
 *
 * Call via `apiCall<void>('ad_test_connection', {})`.
 */
